language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy

# command to run tests
script:
  - python cStress.py -h
