language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

# command to run tests
script:
  - python cStress.py -h
